name: Release Module

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
    uses: sheetdelver/sheetdelver/.github/workflows/module-release.yml@v0.9.1
    with:
      module_id: 'shadowdark'
      core_ref: 'v0.9.1'
